# Generated by Django 4.1.2 on 2022-10-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='age',
            new_name='year',
        ),
    ]
