# Generated by Django 4.1.2 on 2022-10-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(verbose_name='show date'),
        ),
        migrations.AddField(
            model_name='car',
            name='mods',
            field=models.ManyToManyField(to='main_app.mod'),
        ),
    ]
